#!/usr/bin/env bash

# Used to build out our src/ folder for the generator. Should be run anytime commits are pushed to the main <%= themename %> repo.
if [ -d "src" ]; then
	#Remove our current src/ folder if it exists.
	rm -rf "src"
fi

# Clone down a new copy of <%= themename %>
git clone --recursive git@github.com:WebDevStudios/_s.git src

if [ -d "src/.git" ]; then
	rm -rf "src/.git"
fi

if [ -d "src/bower_components" ]; then
	rm -rf "src/bower_components"
fi

if [ -d "src/sassdoc" ]; then
	rm -rf "src/sassdoc"
fi

if [ -f "src/.gitignore" ]; then
	rm "src/.gitignore"
fi

#Explicitly set our local so that sed doesn't thrown an error.
LC_ALL=C

#Do the <%= themename %> replacements to our templating tags.
find src/ -type f -not -name "*.png" -exec sed -i '' "s/'_s'/'<%= shortname %>'/g" {} \;
find src/ -type f -not -name "*.png" -exec sed -i '' 's/_s_/<%= prefixname %>_/g' {} \;
find src/ -type f -not -name "*.png" -exec sed -i '' 's/ _s/ <%= themename %>/g' {} \;
find src/ -type f -not -name "*.png" -exec sed -i '' 's/_s-/<%= shortname %>-/g' {} \;
find src/ -type f -not -name "*.png" -exec sed -i '' 's/Text Domain: .*$/Text Domain: <%= shortname %>/g' {} \;

find src/ -type f -not -name "*.png" -exec sed -i '' 's/"_s"/"<%= shortname %>"/g' {} \;

find src/ -type f -not -name "*.png" -exec sed -i '' 's/"description": ".*"/"description": "<%= descrip %>"/g' {} \;
find src/ -type f -not -name "*.png" -exec sed -i '' 's/Description: .*$/Description: <%= descrip %>/g' {} \;

find src/ -type f -not -name "*.png" -exec sed -i '' 's/Theme URI: .*$/Theme URI: <%= themeuri %>/g' {} \;
find src/ -type f -not -name "*.png" -exec sed -i '' 's/"homepage": ".*"/"homepage": "<%= themeuri %>"/g' {} \;

find src/ -type f -not -name "*.png" -exec sed -i '' 's/Author: .*$/Author: <%= author %>/g' {} \;
find src/ -type f -not -name "*.png" -exec sed -i '' 's/"author": ".*"/"author": "<%= author %>"/g' {} \;

find src/ -type f -not -name "*.png" -exec sed -i '' 's/Author URI: .*$/Author URI: <%= authoruri %>/g' {} \;
